// All PF2e Remaster conditions with their rules summary
// Valued conditions (have a numeric level) vs. simple conditions

export const CONDITIONS = [
  // === VALUED CONDITIONS ===
  {
    id: "clumsy",
    name: "Clumsy",
    valued: true,
    color: "#8B5E3C",
    icon: "🤸",
    category: "physical",
    summary: "Status penalty equal to value to Dex-based rolls and DCs: AC, Reflex saves, ranged attacks, Acrobatics, Stealth, Thievery.",
  },
  {
    id: "confused",
    name: "Confused",
    valued: false,
    color: "#9B59B6",
    icon: "😵",
    category: "mental",
    summary: "Can't use reactions. Each turn: use all actions to Strike nearest creature (DC 11 flat check to avoid self-harm). GM controls movement.",
  },
  {
    id: "drained",
    name: "Drained",
    valued: true,
    color: "#E74C3C",
    icon: "🩸",
    category: "physical",
    summary: "Status penalty equal to value to Con-based DCs and checks (incl. HP per level). Max HP reduced by value × level.",
  },
  {
    id: "dying",
    name: "Dying",
    valued: true,
    color: "#C0392B",
    icon: "💀",
    category: "death",
    summary: "Unconscious. Roll Recovery Check (DC 10 + dying value) each turn. Dying 4 = dead. Losing dying gives Wounded +1.",
  },
  {
    id: "doomed",
    name: "Doomed",
    valued: true,
    color: "#7D1F1F",
    icon: "☠️",
    category: "death",
    summary: "Your soul is in peril. Maximum dying value is reduced by your doomed value. Doomed 3 = immediate death.",
  },
  {
    id: "enfeebled",
    name: "Enfeebled",
    valued: true,
    color: "#795548",
    icon: "💪",
    category: "physical",
    summary: "Status penalty equal to value to Str-based rolls and DCs: attack rolls, damage rolls, Athletics.",
  },
  {
    id: "frightened",
    name: "Frightened",
    valued: true,
    color: "#FF9800",
    icon: "😨",
    category: "mental",
    summary: "Status penalty equal to value to all checks and DCs. Reduces by 1 at end of each of your turns.",
  },
  {
    id: "sickened",
    name: "Sickened",
    valued: true,
    color: "#27AE60",
    icon: "🤢",
    category: "physical",
    summary: "Status penalty equal to value to all checks and DCs. Can Retch as an action (DC = sickened DC) to reduce by 1.",
  },
  {
    id: "slowed",
    name: "Slowed",
    valued: true,
    color: "#3498DB",
    icon: "🐢",
    category: "action",
    summary: "Lose actions each round equal to value (min 0 actions per turn). Reaction loss if slowed 3+.",
  },
  {
    id: "stunned",
    name: "Stunned",
    valued: true,
    color: "#F39C12",
    icon: "⚡",
    category: "action",
    summary: "Lose actions equal to value (then reduce to 0). Stunned overrides slowed. Can't use reactions while stunned.",
  },
  {
    id: "wounded",
    name: "Wounded",
    valued: true,
    color: "#C0392B",
    icon: "🩹",
    category: "death",
    summary: "You've been brought back from dying. If you become dying again, your dying value increases by your wounded value.",
  },
  // === SIMPLE CONDITIONS ===
  {
    id: "blinded",
    name: "Blinded",
    valued: false,
    color: "#2C3E50",
    icon: "🙈",
    category: "sense",
    summary: "Can't see. Automatically critically fail Perception checks requiring sight. –4 status to Perception if sight is only precise sense. Immune to visual effects.",
  },
  {
    id: "broken",
    name: "Broken",
    valued: false,
    color: "#7F8C8D",
    icon: "💔",
    category: "item",
    summary: "Object only. HP reduced to Broken Threshold or below. Can't be used for normal function or grant bonuses.",
  },
  {
    id: "concealed",
    name: "Concealed",
    valued: false,
    color: "#95A5A6",
    icon: "🌫️",
    category: "sense",
    summary: "Still observed but harder to target. Creatures targeting you must succeed at DC 5 flat check or the action is lost.",
  },
  {
    id: "controlled",
    name: "Controlled",
    valued: false,
    color: "#8E44AD",
    icon: "🎮",
    category: "mental",
    summary: "Another creature determines your actions. You can't take free actions or reactions unless your controller allows it.",
  },
  {
    id: "dazzled",
    name: "Dazzled",
    valued: false,
    color: "#F1C40F",
    icon: "✨",
    category: "sense",
    summary: "Everything is concealed to you (DC 5 flat check required when you target anything).",
  },
  {
    id: "deafened",
    name: "Deafened",
    valued: false,
    color: "#BDC3C7",
    icon: "🔇",
    category: "sense",
    summary: "Can't hear. –2 status penalty to Perception vs. sounds. Automatically critically fail auditory Perception checks. 20% chance to lose verbal spells.",
  },
  {
    id: "encumbered",
    name: "Encumbered",
    valued: false,
    color: "#8B6914",
    icon: "⚖️",
    category: "physical",
    summary: "Treated as Clumsy 1. –10-ft penalty to all speeds.",
  },
  {
    id: "fascinated",
    name: "Fascinated",
    valued: false,
    color: "#E91E63",
    icon: "👁️",
    category: "mental",
    summary: "–2 status penalty to Perception and skill checks. Can't take actions with the explore or concentrate trait unless they're related to the fascinating subject.",
  },
  {
    id: "fatigued",
    name: "Fatigued",
    valued: false,
    color: "#607D8B",
    icon: "😴",
    category: "physical",
    summary: "–1 status penalty to AC and saving throws. Can't use exploration activities. Removed after full night's rest.",
  },
  {
    id: "flat-footed",
    name: "Off-Guard",
    valued: false,
    color: "#E67E22",
    icon: "🛡️",
    category: "physical",
    summary: "–2 circumstance penalty to AC. (Formerly 'flat-footed' in pre-Remaster rules.)",
  },
  {
    id: "fleeing",
    name: "Fleeing",
    valued: false,
    color: "#E74C3C",
    icon: "🏃",
    category: "mental",
    summary: "Must spend your actions to get away from the source of fleeing as fast as possible. Can't move toward that source.",
  },
  {
    id: "grabbed",
    name: "Grabbed",
    valued: false,
    color: "#795548",
    icon: "✊",
    category: "physical",
    summary: "Off-Guard and Immobilized. If the grabbing creature moves, you move with it. Ends if the grabber is incapacitated or moves away.",
  },
  {
    id: "hidden",
    name: "Hidden",
    valued: false,
    color: "#455A64",
    icon: "👤",
    category: "sense",
    summary: "Creatures know your general location but can't see you. They must succeed at DC 11 flat check when targeting you.",
  },
  {
    id: "immobilized",
    name: "Immobilized",
    valued: false,
    color: "#546E7A",
    icon: "🔒",
    category: "physical",
    summary: "Can't use actions with the move trait. If forced to move, must succeed at DC 10 flat check or the move is lost.",
  },
  {
    id: "invisible",
    name: "Invisible",
    valued: false,
    color: "#E0E0E0",
    icon: "👻",
    category: "sense",
    summary: "Can't be seen. Creatures must succeed at DC 11 flat check when targeting you. You're hidden even to creatures with precise senses unless they pinpoint your location.",
  },
  {
    id: "observed",
    name: "Observed",
    valued: false,
    color: "#4CAF50",
    icon: "👀",
    category: "sense",
    summary: "Fully detected. Creatures can perceive you precisely. This is the default state.",
  },
  {
    id: "paralyzed",
    name: "Paralyzed",
    valued: false,
    color: "#37474F",
    icon: "🧊",
    category: "physical",
    summary: "Physically unable to act. Lose all actions and reactions. Off-Guard. Automatically critically fail Str and Dex saves.",
  },
  {
    id: "petrified",
    name: "Petrified",
    valued: false,
    color: "#78909C",
    icon: "🗿",
    category: "physical",
    summary: "Turned to stone. Lose all senses, actions, and reactions. Unaffected by most effects. Become an object with Hardness 8 and 115 HP.",
  },
  {
    id: "prone",
    name: "Prone",
    valued: false,
    color: "#A0522D",
    icon: "🪃",
    category: "physical",
    summary: "Off-Guard. –2 circumstance penalty to attack rolls. Must use Crawl to move. Can't Fly or Swim. Melee attackers get +2 circumstance to hit. Ranged attackers get –2.",
  },
  {
    id: "quickened",
    name: "Quickened",
    valued: false,
    color: "#00BCD4",
    icon: "⚡",
    category: "action",
    summary: "Gain 1 extra action each turn. Many effects limit which extra action you can use with the benefit.",
  },
  {
    id: "restrained",
    name: "Restrained",
    valued: false,
    color: "#5D4037",
    icon: "⛓️",
    category: "physical",
    summary: "Off-Guard, Immobilized, and Grabbed. Also can't take actions with the attack or manipulate trait.",
  },
  {
    id: "unconscious",
    name: "Unconscious",
    valued: false,
    color: "#263238",
    icon: "💤",
    category: "death",
    summary: "Sleeping or knocked out. Off-Guard, Blinded, –4 penalty to AC, Perception, and Reflex saves. Can't take actions or reactions.",
  },
  {
    id: "undetected",
    name: "Undetected",
    valued: false,
    color: "#1A237E",
    icon: "🕵️",
    category: "sense",
    summary: "Creatures don't know your location. They must succeed at DC 11 flat check when targeting your space, and must first succeed at Seek to find you.",
  },
];

export const CATEGORY_LABELS = {
  action: "Action Economy",
  physical: "Physical",
  mental: "Mental",
  sense: "Senses & Detection",
  death: "Dying & Death",
  item: "Item",
};

export const CATEGORY_ORDER = ["action", "death", "physical", "mental", "sense", "item"];
